# 本番、開発環境共通の設定
version: '3.8'

services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/etc/logrotate.d/nginx:/etc/logrotate.d/nginx
      - ./proxy/var/log/nginx:/var/log/nginx
      - ./proxy/etc/letsencrypt:/etc/letsencrypt
      - ./proxy/etc/nginx/ticket-keys:/etc/nginx/ticket-keys # 秘密鍵を保存するディレクトリ
    networks:
      - dev_network
    restart: always
    env_file:
      - ./.env

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
        - 8080:8080
    command:
        - start-dev
    depends_on:
      - keycloak-db
    networks:
      - dev_network

  keycloak-db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    networks:
      - dev_network

  minio:
    image: minio/minio
    volumes:
      - ./minio/data:/data # MinIOのデータを保存するディレクトリ
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data
    restart: always

  fluent-bit:
    image: newrelic/newrelic-fluentbit-output:latest
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc
      - ./proxy/var/log/nginx:/var/log/nginx
    environment:
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
    depends_on:
      - nginx-proxy
    networks:
      - dev_network

volumes:
  keycloak-db:

networks:
  dev_network:
    driver: bridge
    name: dev_network

